CREATE TABLE produtos(
id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
sku VARCHAR(50) NOT NULL UNIQUE,
nome VARCHAR(100) NOT NULL,
estoque_atual INTEGER NOT NULL DEFAULT 0,
estoque_minimo INTEGER NOT NULL,
estoque_ideal INTEGER NOT NULL,
preco_unitario NUMERIC(10,2)NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);